name: Backend Lint and Test CI

on: push

defaults:
  run:
    working-directory: ./backend

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Black
      run: ls; black --check "./app"
    - name: Test with Pytest
      run: pytest "./app"
